In [6]:
import numpy as np
import time
L = list(range(100000000))
list_start = time.time()
result = [x*2 for x in L]
list_time = time.time() - list_start

A = np.arange(100000000)
numpy_start = time.time()
res = A * 2
numpy_time = time.time() - numpy_start

list_time,numpy_time


(16.261352062225342, 0.1391737461090088)

In [40]:
# Create Numpy Array
# From list
Arr1 = np.array([1,2,3,4,5])
print(Arr1)
print(type(Arr1))
#Default Functions
zero = np.zeros((3,3))
print(zero)
one = np.ones((4,2))
print(one)
ar = np.arange(10)
print(ar)
ar_even = np.arange(0,10,2)
print(ar_even)
ar_odd = np.arange(1,10,2)
print(ar_odd)
lp = np.linspace(0,2,5)
print(lp)
iden = np.eye(4)
print(iden)



[1 2 3 4 5]
<class 'numpy.ndarray'>
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[1 3 5 7 9]
[0.  0.5 1.  1.5 2. ]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [41]:
# Randon
randf = np.random.rand(2,3)
print(randf)

randin = np.random.randint(1,100,size=(3,3,3))
print(randin)

[[0.50779125 0.94069346 0.75124503]
 [0.25430765 0.80884932 0.53435307]]
[[[63  7 48]
  [56 86 52]
  [16 62 29]]

 [[55 56 27]
  [55 10 28]
  [35 46 76]]

 [[76 86 62]
  [89 48 26]
  [42 56 99]]]
