In [1]:
import numpy as np
import time
L = list(range(1000))
list_start = time.time()
result = [x*2 for x in L]
list_time = time.time() - list_start

A = np.arange(1000)
numpy_start = time.time()
res = A * 2
numpy_time = time.time() - numpy_start

list_time,numpy_time


(0.0, 0.0)

In [40]:
# Create Numpy Array
# From list
Arr1 = np.array([1,2,3,4,5])
print(Arr1)
print(type(Arr1))
#Default Functions
zero = np.zeros((3,3))
print(zero)
one = np.ones((4,2))
print(one)
ar = np.arange(10)
print(ar)
ar_even = np.arange(0,10,2)
print(ar_even)
ar_odd = np.arange(1,10,2)
print(ar_odd)
lp = np.linspace(0,2,5)
print(lp)
iden = np.eye(4)
print(iden)



[1 2 3 4 5]
<class 'numpy.ndarray'>
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[1 3 5 7 9]
[0.  0.5 1.  1.5 2. ]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [41]:
# Randon
randf = np.random.rand(2,3)
print(randf)

randin = np.random.randint(1,100,size=(3,3,3))
print(randin)

[[0.50779125 0.94069346 0.75124503]
 [0.25430765 0.80884932 0.53435307]]
[[[63  7 48]
  [56 86 52]
  [16 62 29]]

 [[55 56 27]
  [55 10 28]
  [35 46 76]]

 [[76 86 62]
  [89 48 26]
  [42 56 99]]]


In [7]:
print(np.arange(2,11,2).astype(int))
print(np.ones((3,3)).astype(int))
print(np.arange(2,11,2).astype(str))

[ 2  4  6  8 10]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
['2' '4' '6' '8' '10']


In [3]:
# Attributes .shape,.size,ndim
arr = np.array([[[10,20,30],
                [40,50,60],
                [70,80,90]]])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)


[[[10 20 30]
  [40 50 60]
  [70 80 90]]]
(1, 3, 3)
9
3


In [23]:
# Indexing and Slicing
print(arr[0,2,0])
print(arr[0:,0:3,0:3])


70
[[[10 20 30]
  [40 50 60]
  [70 80 90]]]


In [33]:
# Mathamatical operations
a = np.array([1,2,3])
b = np.array([1,2,4])
print(a + b)
print(a * b)
print(a -b)
print(a/b)
print(np.sqrt(a))

[2 4 7]
[ 1  4 12]
[ 0  0 -1]
[1.   1.   0.75]
[1.         1.41421356 1.73205081]


In [59]:
# Array Methods
# min, max , mean, median, std, axis operation
a = np.arange(0,100,6)
print(a)
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
b = np.array([[1,2,3],
              [5,7,8]])
print(np.sum(b))
print(np.sum(b,axis=0))
print(np.sum(b,axis=1))

[ 0  6 12 18 24 30 36 42 48 54 60 66 72 78 84 90 96]
0
96
48.0
48.0
29.393876913398138
26
[ 6  9 11]
[ 6 20]


In [ ]:
# Broadcasting and reshaping
arr1 = np.array([[1,2,3],
                [4,5,6]])
print(arr1)
print(arr1 + 10)

[[1 2 3]
 [4 5 6]]
[[11 12 13]
 [14 15 16]]


In [80]:
# Reshape
arr2 = np.arange(0,12)
print(arr2)
print(arr2.reshape(2,6,1))
print(arr2.reshape(2,6,1,1).ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]]]
4


In [92]:
a = np.array([1,2,3])
b = np.array([1,2,4])
print(np.concatenate((a,b)))
print(np.vstack((a,b)))
print(np.hstack((a,b)))
c = np.arange(1,100)
print(c)
print(np.sort(b))
print(np.sort(b)[::-1])

[1 2 3 1 2 4]
[[1 2 3]
 [1 2 4]]
[1 2 3 1 2 4]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
[1 2 4]
[4 2 1]


In [95]:
# Advance Tricks
d = np.arange(1,10)
print(d[d > 5])
e = [1,2,3,12,4,2,9]
print(np.unique(e))

[6 7 8 9]
[ 1  2  3  4  9 12]


In [98]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

C = np.matmul(A, B)
D = np.matmul(B, A)
# or C = A @ B

print(C)
print(D)

[[19 22]
 [43 50]]
[[23 34]
 [31 46]]
