In [2]:
# Install Numpy
!pip install numpy

In [6]:
#Basic Numpy Array
import numpy as np
myArray = np.array([1, 2, 3, 4, 5])
print(myArray)
print(type(myArray))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [17]:
# Multidimensional Array
myList1 = [1,2,3,4,5]
myList2 = [6,7,8,9,10]
myList3 = [11,12,13,14,15]
multiArray = np.array([myList1, myList2, myList3])
print(multiArray)
print(multiArray.shape)
print(multiArray.ndim)
print(multiArray.reshape(5,3))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)
2
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [27]:
# Multidimensional Array - 2
myList1 = [1,2,3,4]
myList2 = [6,7,8,9]
myList3 = [11,12,13,14]
myList4 = [16,17,18,19]
multiArray = np.array([myList1, myList2, myList3, myList4])
print(multiArray)
print(multiArray.shape)
print(multiArray.ndim)
print(multiArray.reshape(2,8))

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]]
(4, 4)
2
[[ 1  2  3  4  6  7  8  9]
 [11 12 13 14 16 17 18 19]]


In [33]:
# Numpy Array Operations
sudheerList = [1,2,3,4,5]
sudheerArray = np.array(sudheerList)
print(sudheerArray)
print(sudheerArray + 5)
print(type(sudheerArray))
print(sudheerArray.shape)

[1 2 3 4 5]
[ 6  7  8  9 10]
<class 'numpy.ndarray'>
(5,)


In [46]:
# Multidimensional Array
list_1 = [1,2,3,4,5]
list_2 = [6,7,8,9,10]
list_3 = [11,12,13,14,15]
list_4 = [16,17,18,19,20]
multiArray = np.array([list_1, list_2, list_3, list_4])
print(multiArray)
print(multiArray.reshape(1,20))
print("=========================")
print(multiArray.reshape(2,10))
print("=========================")
print(multiArray.reshape(4,5))
print("=========================")
print(multiArray.reshape(5,4))
print("=========================")
print(multiArray.reshape(10,2))
print("=========================")
print(multiArray.reshape(20,1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]]


In [81]:
# Numpy Indexing and Slicing
myList1 = [1,2,3,4,5]
myList2 = [6,7,8,9,10]
myList3 = [11,12,13,14,15]
multiArray = np.array([myList1, myList2, myList3])
print(multiArray)
print("=========================")
print(multiArray.reshape(5,3))
print("=========================")
print(multiArray.reshape(5,3)[2][0])
print("=========================")
print(multiArray[0:3,0:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
7
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [94]:
multiArray = np.array([myList1, myList2, myList3])
#print(multiArray)
print("=========================")
print(multiArray[1:3,0:1])
print("=========================")
print(np.arange(1,100,step=3))

[[ 6]
 [11]]
[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76 79 82 85 88 91 94 97]


In [105]:
# Numpy linespace
print(np.linspace(1,100,6))

[  1.   20.8  40.6  60.4  80.2 100. ]


In [117]:
# Broadcasting
myArray = np.array([1,2,3,4,5])
print(myArray)
print(myArray + 5)
myArray[2:1] = 6
print(myArray)

[1 2 3 4 5]
[ 6  7  8  9 10]
[1 2 3 4 5]


In [125]:
# copy and view
myArray1 = np.array([1,2,3,4,5]) 
myArray2 = myArray1 # This is a view, not a copy
myArray3 = myArray1.copy() # This is a copy
print("Original Array:", myArray1)
print("View Array:", myArray2)
print("Copy Array:", myArray3)
myArray2[0] = 10    
print("After modifying the view:")
print("Original Array:", myArray1)  # This will change
print("View Array:", myArray2)      # This will change
print("Copy Array:", myArray3)      # This will NOT change


Original Array: [1 2 3 4 5]
View Array: [1 2 3 4 5]
Copy Array: [1 2 3 4 5]
After modifying the view:
Original Array: [10  2  3  4  5]
View Array: [10  2  3  4  5]
Copy Array: [1 2 3 4 5]


In [134]:
# reshape and flatten
myArray = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original Array:")  
print(myArray)
print("Reshaped Array (1,9):")
print(myArray.reshape(1,9))
print(np.arange(1,17).reshape(8,2))

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped Array (1,9):
[[1 2 3 4 5 6 7 8 9]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [140]:
# Numpy Multiply
array1 = np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9,10])
result = array1 * array2
print("Array 1:", array1)
print("Array 2:", array2)    
print("Element-wise Multiplication Result:", result)

Array 1: [1 2 3 4 5]
Array 2: [ 6  7  8  9 10]
Element-wise Multiplication Result: [ 6 14 24 36 50]


In [144]:
#Numpy Once
print(np.ones(10,dtype=int).reshape(2,5))

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [145]:
#Numpy Random
print(np.random.rand(3,3))

[[0.29604911 0.44620731 0.60332814]
 [0.64945384 0.52470972 0.44345117]
 [0.64548633 0.48556443 0.8041723 ]]


In [147]:
# Initialize the generator
rng = np.random.default_rng()
print(rng)

# Single random integer between 0 (inclusive) and 10 (exclusive)
val = rng.integers(0, 10)
print(val)

# 1D array of 5 integers between 10 and 20 (exclusive)
arr = rng.integers(low=10, high=20, size=5)
print(arr)

# 2x3 matrix of random integers, including the high value (endpoint=True)
matrix = rng.integers(0, 10, size=(2, 3), endpoint=True)
print(matrix)

Generator(PCG64)
7
[12 12 13 11 11]
[[9 7 8]
 [9 7 7]]


In [148]:
# Numpy randint
print(np.random.randint(0, 10, size=(2, 3)))

[[6 8 4]
 [9 1 8]]
